language: c
env:
  global:
    - secure: C12rp1LgtgILMWfyDSqPz2rn57qm+/9v+ZNECjq2zjmWz8aAUTgK+T4iWgD/EtzWjNt9CfNOMhtHjZIzUaX6heTKUwxLcGssVKE4rNXKaQG+VyBxSz5JD6HvVhvHptbNoY7r+HdZ6kTRob2nFftdQ1/yC01i9h244uJqOSfczs8=
    - LD_LIBRARY_PATH=/usr/local/lib
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo build --verbose
  - cargo test --verbose
  - ./target/test/iter_mdo
  - cargo doc --verbose
after_script:
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
