language: rust
env:
  global:
    - secure: C12rp1LgtgILMWfyDSqPz2rn57qm+/9v+ZNECjq2zjmWz8aAUTgK+T4iWgD/EtzWjNt9CfNOMhtHjZIzUaX6heTKUwxLcGssVKE4rNXKaQG+VyBxSz5JD6HvVhvHptbNoY7r+HdZ6kTRob2nFftdQ1/yC01i9h244uJqOSfczs8=
script: |
  cargo build -v &&
  cargo test -v &&
  ./target/examples/iter_mdo
after_script: |
  cargo doc -v &&
  (cd target && curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh)
